//! Persistent conversation storage backed by SQLite.
//!
//! Stores conversations, messages, intents, and edit decisions. Each
//! conversation is linked to a file path + line range. Full-text search
//! is available over message content via SQLite FTS5.

use anyhow::Result;
use rusqlite::{params, Connection};
use std::path::Path;

/// Unique conversation identifier.
pub type ConversationId = String;

/// A conversation thread attached to a code range.
#[derive(Debug, Clone)]
pub struct Conversation {
    /// Unique identifier for this conversation.
    pub id: ConversationId,
    /// Path to the file this conversation is attached to.
    pub file_path: String,
    /// First line of the code range.
    pub start_line: usize,
    /// Last line of the code range.
    pub end_line: usize,
    /// Git commit hash at conversation creation time.
    pub git_commit: Option<String>,
    /// Git branch name at conversation creation time.
    pub branch: Option<String>,
    /// ISO-8601 timestamp when the conversation was created.
    pub created_at: String,
    /// ISO-8601 timestamp of the last update.
    pub updated_at: String,
    /// Optional AI-generated summary of the conversation.
    pub summary: Option<String>,
}

/// Role in a conversation message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MessageRole {
    /// A message expressing the human's intent.
    HumanIntent,
    /// A response generated by the AI.
    AiResponse,
    /// A system-level message.
    System,
}

impl MessageRole {
    fn as_str(&self) -> &'static str {
        match self {
            MessageRole::HumanIntent => "human_intent",
            MessageRole::AiResponse => "ai_response",
            MessageRole::System => "system",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "human_intent" => MessageRole::HumanIntent,
            "ai_response" => MessageRole::AiResponse,
            _ => MessageRole::System,
        }
    }
}

impl std::fmt::Display for MessageRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MessageRole::HumanIntent => write!(f, "You"),
            MessageRole::AiResponse => write!(f, "AI"),
            MessageRole::System => write!(f, "System"),
        }
    }
}

/// A single message within a conversation.
#[derive(Debug, Clone)]
pub struct ConversationMessage {
    /// Unique message identifier.
    pub id: String,
    /// The conversation this message belongs to.
    pub conversation_id: ConversationId,
    /// Who sent this message.
    pub role: MessageRole,
    /// The message text.
    pub content: String,
    /// ISO-8601 timestamp when the message was created.
    pub created_at: String,
    /// AI model used to generate this message, if applicable.
    pub model: Option<String>,
}

/// A recorded intent.
#[derive(Debug, Clone)]
pub struct Intent {
    /// Unique intent identifier.
    pub id: String,
    /// The conversation this intent belongs to.
    pub conversation_id: ConversationId,
    /// The natural-language intent text.
    pub intent_text: String,
    /// File path the intent applies to.
    pub file_path: String,
    /// First line of the target range.
    pub start_line: usize,
    /// Last line of the target range.
    pub end_line: usize,
    /// ISO-8601 timestamp when the intent was recorded.
    pub created_at: String,
}

/// The outcome of reviewing an AI proposal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Decision {
    /// The proposed edit was accepted.
    Accepted,
    /// The proposed edit was rejected.
    Rejected,
}

impl Decision {
    fn as_str(&self) -> &'static str {
        match self {
            Decision::Accepted => "accepted",
            Decision::Rejected => "rejected",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "accepted" => Decision::Accepted,
            _ => Decision::Rejected,
        }
    }
}

impl std::fmt::Display for Decision {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// A logged accept/reject decision.
#[derive(Debug, Clone)]
pub struct EditDecision {
    /// Unique decision identifier.
    pub id: String,
    /// The conversation this decision belongs to.
    pub conversation_id: ConversationId,
    /// The intent that prompted this decision, if any.
    pub intent_id: Option<String>,
    /// Whether the edit was accepted or rejected.
    pub decision: Decision,
    /// The original text before the proposed change.
    pub original_text: Option<String>,
    /// The AI-proposed replacement text.
    pub proposed_text: Option<String>,
    /// File path where the edit applies.
    pub file_path: String,
    /// First line of the edit range.
    pub start_line: usize,
    /// Last line of the edit range.
    pub end_line: usize,
    /// ISO-8601 timestamp when the decision was made.
    pub created_at: String,
    /// Git commit hash at decision time.
    pub git_commit: Option<String>,
    /// Git branch name at decision time.
    pub branch: Option<String>,
}

/// Persistent storage for conversations and edit decisions.
pub struct ConversationStore {
    conn: Connection,
}

impl ConversationStore {
    /// Open (or create) the database at the given path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        if let Some(parent) = path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(path)?;
        let store = Self { conn };
        store.migrate()?;
        Ok(store)
    }

    /// Open an in-memory database (for testing).
    pub fn in_memory() -> Result<Self> {
        let conn = Connection::open_in_memory()?;
        let store = Self { conn };
        store.migrate()?;
        Ok(store)
    }

    /// Create or update tables.
    fn migrate(&self) -> Result<()> {
        self.conn.execute_batch("PRAGMA journal_mode=WAL;")?;

        self.conn.execute_batch(
            "
            CREATE TABLE IF NOT EXISTS conversations (
                id          TEXT PRIMARY KEY,
                file_path   TEXT NOT NULL,
                start_line  INTEGER NOT NULL,
                end_line    INTEGER NOT NULL,
                git_commit  TEXT,
                created_at  TEXT NOT NULL,
                updated_at  TEXT NOT NULL,
                summary     TEXT
            );

            CREATE TABLE IF NOT EXISTS messages (
                id              TEXT PRIMARY KEY,
                conversation_id TEXT NOT NULL REFERENCES conversations(id),
                role            TEXT NOT NULL,
                content         TEXT NOT NULL,
                created_at      TEXT NOT NULL,
                model           TEXT
            );

            CREATE TABLE IF NOT EXISTS intents (
                id              TEXT PRIMARY KEY,
                conversation_id TEXT NOT NULL REFERENCES conversations(id),
                intent_text     TEXT NOT NULL,
                file_path       TEXT NOT NULL,
                start_line      INTEGER NOT NULL,
                end_line        INTEGER NOT NULL,
                created_at      TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS edit_decisions (
                id              TEXT PRIMARY KEY,
                conversation_id TEXT NOT NULL REFERENCES conversations(id),
                intent_id       TEXT,
                decision        TEXT NOT NULL,
                original_text   TEXT,
                proposed_text   TEXT,
                file_path       TEXT NOT NULL,
                start_line      INTEGER NOT NULL,
                end_line        INTEGER NOT NULL,
                created_at      TEXT NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_conv_file ON conversations(file_path);
            CREATE INDEX IF NOT EXISTS idx_conv_lines ON conversations(file_path, start_line, end_line);
            CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id);
            CREATE INDEX IF NOT EXISTS idx_decisions_created ON edit_decisions(created_at);
            CREATE INDEX IF NOT EXISTS idx_intents_conv ON intents(conversation_id);
            ",
        )?;

        // Backward-compatible migrations for new columns.
        let _ = self
            .conn
            .execute_batch("ALTER TABLE conversations ADD COLUMN branch TEXT;");
        let _ = self
            .conn
            .execute_batch("ALTER TABLE edit_decisions ADD COLUMN git_commit TEXT;");
        let _ = self
            .conn
            .execute_batch("ALTER TABLE edit_decisions ADD COLUMN branch TEXT;");

        Ok(())
    }

    // ── Conversation operations ───────────────────────────────────

    /// Create a new conversation attached to a file:line range.
    pub fn create_conversation(
        &self,
        file_path: &str,
        start_line: usize,
        end_line: usize,
        git_commit: Option<&str>,
        branch: Option<&str>,
    ) -> Result<Conversation> {
        let id = uuid::Uuid::new_v4().to_string();
        let now = now_iso();
        self.conn.execute(
            "INSERT INTO conversations (id, file_path, start_line, end_line, git_commit, branch, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            params![id, file_path, start_line as i64, end_line as i64, git_commit, branch, now, now],
        )?;
        Ok(Conversation {
            id,
            file_path: file_path.to_string(),
            start_line,
            end_line,
            git_commit: git_commit.map(String::from),
            branch: branch.map(String::from),
            created_at: now.clone(),
            updated_at: now,
            summary: None,
        })
    }

    /// Find conversations overlapping a line range in a file.
    pub fn conversations_for_range(
        &self,
        file_path: &str,
        start_line: usize,
        end_line: usize,
    ) -> Result<Vec<Conversation>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, start_line, end_line, git_commit, branch, created_at, updated_at, summary
             FROM conversations
             WHERE file_path = ?1 AND start_line <= ?3 AND end_line >= ?2
             ORDER BY updated_at DESC",
        )?;
        let rows = stmt.query_map(
            params![file_path, start_line as i64, end_line as i64],
            row_to_conversation,
        )?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Find conversations for a specific file.
    pub fn conversations_for_file(&self, file_path: &str) -> Result<Vec<Conversation>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, start_line, end_line, git_commit, branch, created_at, updated_at, summary
             FROM conversations WHERE file_path = ?1 ORDER BY updated_at DESC",
        )?;
        let rows = stmt.query_map(params![file_path], row_to_conversation)?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Get a conversation by ID.
    pub fn get_conversation(&self, id: &str) -> Result<Option<Conversation>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, start_line, end_line, git_commit, branch, created_at, updated_at, summary
             FROM conversations WHERE id = ?1",
        )?;
        let mut rows = stmt.query_map(params![id], row_to_conversation)?;
        match rows.next() {
            Some(row) => Ok(Some(row?)),
            None => Ok(None),
        }
    }

    /// Update the summary for a conversation.
    pub fn update_summary(&self, id: &str, summary: &str) -> Result<()> {
        self.conn.execute(
            "UPDATE conversations SET summary = ?1, updated_at = ?2 WHERE id = ?3",
            params![summary, now_iso(), id],
        )?;
        Ok(())
    }

    // ── Message operations ────────────────────────────────────────

    /// Add a message to a conversation.
    pub fn add_message(
        &self,
        conversation_id: &str,
        role: MessageRole,
        content: &str,
        model: Option<&str>,
    ) -> Result<ConversationMessage> {
        let id = uuid::Uuid::new_v4().to_string();
        let now = now_iso();
        self.conn.execute(
            "INSERT INTO messages (id, conversation_id, role, content, created_at, model)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![id, conversation_id, role.as_str(), content, now, model],
        )?;
        // Touch the conversation's updated_at.
        self.conn.execute(
            "UPDATE conversations SET updated_at = ?1 WHERE id = ?2",
            params![now, conversation_id],
        )?;
        Ok(ConversationMessage {
            id,
            conversation_id: conversation_id.to_string(),
            role,
            content: content.to_string(),
            created_at: now,
            model: model.map(String::from),
        })
    }

    /// Get all messages in a conversation, ordered by time.
    pub fn messages_for_conversation(
        &self,
        conversation_id: &str,
    ) -> Result<Vec<ConversationMessage>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, conversation_id, role, content, created_at, model
             FROM messages WHERE conversation_id = ?1 ORDER BY created_at ASC",
        )?;
        let rows = stmt.query_map(params![conversation_id], |row| {
            Ok(ConversationMessage {
                id: row.get(0)?,
                conversation_id: row.get(1)?,
                role: MessageRole::from_str(&row.get::<_, String>(2)?),
                content: row.get(3)?,
                created_at: row.get(4)?,
                model: row.get(5)?,
            })
        })?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    // ── Intent operations ─────────────────────────────────────────

    /// Record an intent.
    pub fn record_intent(
        &self,
        conversation_id: &str,
        intent_text: &str,
        file_path: &str,
        start_line: usize,
        end_line: usize,
    ) -> Result<Intent> {
        let id = uuid::Uuid::new_v4().to_string();
        let now = now_iso();
        self.conn.execute(
            "INSERT INTO intents (id, conversation_id, intent_text, file_path, start_line, end_line, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
            params![id, conversation_id, intent_text, file_path, start_line as i64, end_line as i64, now],
        )?;
        Ok(Intent {
            id,
            conversation_id: conversation_id.to_string(),
            intent_text: intent_text.to_string(),
            file_path: file_path.to_string(),
            start_line,
            end_line,
            created_at: now,
        })
    }

    /// Get the most recent intent for a conversation.
    pub fn latest_intent(&self, conversation_id: &str) -> Result<Option<Intent>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, conversation_id, intent_text, file_path, start_line, end_line, created_at
             FROM intents WHERE conversation_id = ?1 ORDER BY created_at DESC LIMIT 1",
        )?;
        let mut rows = stmt.query_map(params![conversation_id], row_to_intent)?;
        match rows.next() {
            Some(row) => Ok(Some(row?)),
            None => Ok(None),
        }
    }

    // ── Decision logging ──────────────────────────────────────────

    /// Log an accept/reject decision.
    #[allow(clippy::too_many_arguments)]
    pub fn log_decision(
        &self,
        conversation_id: &str,
        intent_id: Option<&str>,
        decision: Decision,
        original_text: Option<&str>,
        proposed_text: Option<&str>,
        file_path: &str,
        start_line: usize,
        end_line: usize,
        git_commit: Option<&str>,
        branch: Option<&str>,
    ) -> Result<EditDecision> {
        let id = uuid::Uuid::new_v4().to_string();
        let now = now_iso();
        self.conn.execute(
            "INSERT INTO edit_decisions (id, conversation_id, intent_id, decision, original_text, proposed_text, file_path, start_line, end_line, created_at, git_commit, branch)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)",
            params![id, conversation_id, intent_id, decision.as_str(), original_text, proposed_text, file_path, start_line as i64, end_line as i64, now, git_commit, branch],
        )?;
        Ok(EditDecision {
            id,
            conversation_id: conversation_id.to_string(),
            intent_id: intent_id.map(String::from),
            decision,
            original_text: original_text.map(String::from),
            proposed_text: proposed_text.map(String::from),
            file_path: file_path.to_string(),
            start_line,
            end_line,
            created_at: now,
            git_commit: git_commit.map(String::from),
            branch: branch.map(String::from),
        })
    }

    /// Query recent decisions, optionally filtered by type.
    pub fn query_decisions(
        &self,
        since_days: Option<u32>,
        decision_filter: Option<Decision>,
    ) -> Result<Vec<EditDecision>> {
        let since = since_days
            .map(|d| {
                let secs = d as u64 * 86400;
                let ts = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs()
                    - secs;
                // Approximate ISO format for comparison.
                format!(
                    "{}-{:02}-{:02}",
                    1970 + ts / 31536000,
                    (ts % 31536000) / 2592000 + 1,
                    (ts % 2592000) / 86400 + 1
                )
            })
            .unwrap_or_else(|| "1970-01-01".to_string());

        let decision_str = decision_filter.map(|d| d.as_str().to_string());

        let sql = if decision_str.is_some() {
            "SELECT id, conversation_id, intent_id, decision, original_text, proposed_text, file_path, start_line, end_line, created_at, git_commit, branch
             FROM edit_decisions WHERE created_at >= ?1 AND decision = ?2 ORDER BY created_at DESC"
        } else {
            "SELECT id, conversation_id, intent_id, decision, original_text, proposed_text, file_path, start_line, end_line, created_at, git_commit, branch
             FROM edit_decisions WHERE created_at >= ?1 ORDER BY created_at DESC"
        };

        let mut stmt = self.conn.prepare(sql)?;

        let rows = if let Some(ref dec) = decision_str {
            stmt.query_map(params![since, dec], row_to_decision)?
        } else {
            stmt.query_map(params![since], row_to_decision)?
        };

        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Count recent rejections and find repeated patterns.
    pub fn rejection_patterns(&self, days: u32) -> Result<Vec<(String, usize)>> {
        let mut stmt = self.conn.prepare(
            "SELECT i.intent_text, COUNT(*) as cnt
             FROM edit_decisions d
             JOIN intents i ON d.intent_id = i.id
             WHERE d.decision = 'rejected'
               AND d.created_at >= datetime('now', ?1)
             GROUP BY LOWER(TRIM(i.intent_text))
             HAVING cnt >= 2
             ORDER BY cnt DESC",
        )?;
        let modifier = format!("-{} days", days);
        let rows = stmt.query_map(params![modifier], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, usize>(1)?))
        })?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    // ── Search ────────────────────────────────────────────────────

    /// Search conversation messages by content (simple LIKE search).
    pub fn search(&self, query: &str) -> Result<Vec<(ConversationMessage, Conversation)>> {
        let pattern = format!("%{query}%");
        let mut stmt = self.conn.prepare(
            "SELECT m.id, m.conversation_id, m.role, m.content, m.created_at, m.model,
                    c.id, c.file_path, c.start_line, c.end_line, c.git_commit, c.branch, c.created_at, c.updated_at, c.summary
             FROM messages m
             JOIN conversations c ON m.conversation_id = c.id
             WHERE m.content LIKE ?1
             ORDER BY m.created_at DESC
             LIMIT 50",
        )?;
        let rows = stmt.query_map(params![pattern], |row| {
            let msg = ConversationMessage {
                id: row.get(0)?,
                conversation_id: row.get(1)?,
                role: MessageRole::from_str(&row.get::<_, String>(2)?),
                content: row.get(3)?,
                created_at: row.get(4)?,
                model: row.get(5)?,
            };
            let conv = Conversation {
                id: row.get(6)?,
                file_path: row.get(7)?,
                start_line: row.get::<_, i64>(8)? as usize,
                end_line: row.get::<_, i64>(9)? as usize,
                git_commit: row.get(10)?,
                branch: row.get(11)?,
                created_at: row.get(12)?,
                updated_at: row.get(13)?,
                summary: row.get(14)?,
            };
            Ok((msg, conv))
        })?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    // ── Conversation retrieval ────────────────────────────────────

    /// Find the conversation that produced code at a given line.
    pub fn conversation_for_code(
        &self,
        file_path: &str,
        line: usize,
    ) -> Result<Option<(Conversation, Vec<ConversationMessage>)>> {
        // Find the most recent accepted decision covering this line.
        let mut stmt = self.conn.prepare(
            "SELECT conversation_id FROM edit_decisions
             WHERE file_path = ?1 AND start_line <= ?2 AND end_line >= ?2
               AND decision = 'accepted'
             ORDER BY created_at DESC LIMIT 1",
        )?;
        let conv_id: Option<String> = stmt
            .query_map(params![file_path, line as i64], |row| row.get(0))
            .ok()
            .and_then(|mut rows| rows.next())
            .and_then(|r| r.ok());

        if let Some(cid) = conv_id {
            if let Some(conv) = self.get_conversation(&cid)? {
                let messages = self.messages_for_conversation(&cid)?;
                return Ok(Some((conv, messages)));
            }
        }

        // Fall back to conversations overlapping this line.
        let convs = self.conversations_for_range(file_path, line, line)?;
        if let Some(conv) = convs.into_iter().next() {
            let messages = self.messages_for_conversation(&conv.id)?;
            return Ok(Some((conv, messages)));
        }

        Ok(None)
    }

    /// Retrieve all conversations ordered by most recently updated, with stats.
    ///
    /// Returns `(conversation, files_changed_count, message_count)` tuples.
    pub fn all_conversations_with_stats(
        &self,
        limit: usize,
    ) -> Result<Vec<(Conversation, usize, usize)>> {
        let mut stmt = self.conn.prepare(
            "SELECT c.id, c.file_path, c.start_line, c.end_line, c.git_commit, c.branch,
                    c.created_at, c.updated_at, c.summary,
                    COALESCE(d.file_count, 0) AS files_changed,
                    COALESCE(m.msg_count, 0) AS message_count
             FROM conversations c
             LEFT JOIN (
                 SELECT conversation_id, COUNT(DISTINCT file_path) AS file_count
                 FROM edit_decisions GROUP BY conversation_id
             ) d ON d.conversation_id = c.id
             LEFT JOIN (
                 SELECT conversation_id, COUNT(*) AS msg_count
                 FROM messages GROUP BY conversation_id
             ) m ON m.conversation_id = c.id
             ORDER BY c.updated_at DESC
             LIMIT ?1",
        )?;
        let rows = stmt.query_map(params![limit as i64], |row| {
            let conv = Conversation {
                id: row.get(0)?,
                file_path: row.get(1)?,
                start_line: row.get::<_, i64>(2)? as usize,
                end_line: row.get::<_, i64>(3)? as usize,
                git_commit: row.get(4)?,
                branch: row.get(5)?,
                created_at: row.get(6)?,
                updated_at: row.get(7)?,
                summary: row.get(8)?,
            };
            let files_changed = row.get::<_, i64>(9)? as usize;
            let message_count = row.get::<_, i64>(10)? as usize;
            Ok((conv, files_changed, message_count))
        })?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    /// Find or create a chat conversation (uses `__chat__` as the file path).
    ///
    /// Returns the most recent `__chat__` conversation, or creates a new one
    /// if none exists.
    pub fn find_or_create_chat_conversation(&self, branch: Option<&str>) -> Result<Conversation> {
        let mut stmt = self.conn.prepare(
            "SELECT id, file_path, start_line, end_line, git_commit, branch, created_at, updated_at, summary
             FROM conversations WHERE file_path = '__chat__'
             ORDER BY updated_at DESC LIMIT 1",
        )?;
        let existing: Option<Conversation> = stmt
            .query_map([], row_to_conversation)?
            .next()
            .transpose()?;

        match existing {
            Some(conv) => Ok(conv),
            None => self.create_conversation("__chat__", 0, 0, None, branch),
        }
    }

    /// Get lines that have conversation history (for gutter markers).
    pub fn lines_with_conversations(&self, file_path: &str) -> Result<Vec<(usize, usize)>> {
        let mut stmt = self.conn.prepare(
            "SELECT DISTINCT start_line, end_line FROM conversations WHERE file_path = ?1",
        )?;
        let rows = stmt.query_map(params![file_path], |row| {
            Ok((
                row.get::<_, i64>(0)? as usize,
                row.get::<_, i64>(1)? as usize,
            ))
        })?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }
}

// ── Helper functions ──────────────────────────────────────────────

fn now_iso() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let secs = now.as_secs();
    // Simple ISO 8601 timestamp.
    let days = secs / 86400;
    let time = secs % 86400;
    let hours = time / 3600;
    let minutes = (time % 3600) / 60;
    let seconds = time % 60;

    // Approximate date calculation (sufficient for ordering).
    let mut year = 1970u64;
    let mut remaining_days = days;
    loop {
        let days_in_year = if year % 4 == 0 && (year % 100 != 0 || year % 400 == 0) {
            366
        } else {
            365
        };
        if remaining_days < days_in_year {
            break;
        }
        remaining_days -= days_in_year;
        year += 1;
    }
    let month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    let is_leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
    let mut month = 1u64;
    for (i, &md) in month_days.iter().enumerate() {
        let md = if i == 1 && is_leap { 29 } else { md };
        if remaining_days < md {
            break;
        }
        remaining_days -= md;
        month += 1;
    }
    let day = remaining_days + 1;

    format!("{year:04}-{month:02}-{day:02}T{hours:02}:{minutes:02}:{seconds:02}Z")
}

fn row_to_conversation(row: &rusqlite::Row<'_>) -> rusqlite::Result<Conversation> {
    Ok(Conversation {
        id: row.get(0)?,
        file_path: row.get(1)?,
        start_line: row.get::<_, i64>(2)? as usize,
        end_line: row.get::<_, i64>(3)? as usize,
        git_commit: row.get(4)?,
        branch: row.get(5)?,
        created_at: row.get(6)?,
        updated_at: row.get(7)?,
        summary: row.get(8)?,
    })
}

fn row_to_intent(row: &rusqlite::Row<'_>) -> rusqlite::Result<Intent> {
    Ok(Intent {
        id: row.get(0)?,
        conversation_id: row.get(1)?,
        intent_text: row.get(2)?,
        file_path: row.get(3)?,
        start_line: row.get::<_, i64>(4)? as usize,
        end_line: row.get::<_, i64>(5)? as usize,
        created_at: row.get(6)?,
    })
}

fn row_to_decision(row: &rusqlite::Row<'_>) -> rusqlite::Result<EditDecision> {
    Ok(EditDecision {
        id: row.get(0)?,
        conversation_id: row.get(1)?,
        intent_id: row.get(2)?,
        decision: Decision::from_str(&row.get::<_, String>(3)?),
        original_text: row.get(4)?,
        proposed_text: row.get(5)?,
        file_path: row.get(6)?,
        start_line: row.get::<_, i64>(7)? as usize,
        end_line: row.get::<_, i64>(8)? as usize,
        created_at: row.get(9)?,
        git_commit: row.get(10)?,
        branch: row.get(11)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_and_query_conversation() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 10, 20, None, None)
            .unwrap();
        assert_eq!(conv.file_path, "test.rs");
        assert_eq!(conv.start_line, 10);

        let found = store.conversations_for_range("test.rs", 15, 15).unwrap();
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].id, conv.id);
    }

    #[test]
    fn test_messages() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, None, None)
            .unwrap();

        store
            .add_message(&conv.id, MessageRole::HumanIntent, "Fix the bug", None)
            .unwrap();
        store
            .add_message(
                &conv.id,
                MessageRole::AiResponse,
                "Here is the fix",
                Some("claude"),
            )
            .unwrap();

        let msgs = store.messages_for_conversation(&conv.id).unwrap();
        assert_eq!(msgs.len(), 2);
        assert_eq!(msgs[0].role, MessageRole::HumanIntent);
        assert_eq!(msgs[1].role, MessageRole::AiResponse);
    }

    #[test]
    fn test_intent_and_decision() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, None, None)
            .unwrap();
        let intent = store
            .record_intent(&conv.id, "Fix error handling", "test.rs", 5, 8)
            .unwrap();

        let decision = store
            .log_decision(
                &conv.id,
                Some(&intent.id),
                Decision::Accepted,
                Some("old code"),
                Some("new code"),
                "test.rs",
                5,
                8,
                None,
                None,
            )
            .unwrap();

        assert_eq!(decision.decision, Decision::Accepted);

        let decisions = store.query_decisions(None, None).unwrap();
        assert_eq!(decisions.len(), 1);
    }

    #[test]
    fn test_search() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, None, None)
            .unwrap();
        store
            .add_message(
                &conv.id,
                MessageRole::HumanIntent,
                "Fix the error handling in process_event",
                None,
            )
            .unwrap();

        let results = store.search("error handling").unwrap();
        assert_eq!(results.len(), 1);
        assert!(results[0].0.content.contains("error handling"));
    }

    #[test]
    fn test_conversation_for_code() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 5, 15, None, None)
            .unwrap();
        let intent = store
            .record_intent(&conv.id, "Refactor", "test.rs", 5, 15)
            .unwrap();
        store
            .log_decision(
                &conv.id,
                Some(&intent.id),
                Decision::Accepted,
                None,
                None,
                "test.rs",
                5,
                15,
                None,
                None,
            )
            .unwrap();

        let result = store.conversation_for_code("test.rs", 10).unwrap();
        assert!(result.is_some());
        let (c, _) = result.unwrap();
        assert_eq!(c.id, conv.id);
    }

    #[test]
    fn test_lines_with_conversations() {
        let store = ConversationStore::in_memory().unwrap();
        store
            .create_conversation("test.rs", 5, 15, None, None)
            .unwrap();
        store
            .create_conversation("test.rs", 30, 40, None, None)
            .unwrap();

        let lines = store.lines_with_conversations("test.rs").unwrap();
        assert_eq!(lines.len(), 2);
    }

    #[test]
    fn test_all_conversations_with_stats() {
        let store = ConversationStore::in_memory().unwrap();

        // Create two conversations.
        let conv1 = store
            .create_conversation("foo.rs", 0, 10, None, None)
            .unwrap();
        let conv2 = store
            .create_conversation("bar.rs", 5, 20, None, None)
            .unwrap();

        // Add messages to conv1.
        store
            .add_message(&conv1.id, MessageRole::HumanIntent, "hello", None)
            .unwrap();
        store
            .add_message(&conv1.id, MessageRole::AiResponse, "hi", Some("claude"))
            .unwrap();

        // Add a decision to conv1 (file_path = "foo.rs").
        store
            .log_decision(
                &conv1.id,
                None,
                Decision::Accepted,
                None,
                None,
                "foo.rs",
                0,
                5,
                None,
                None,
            )
            .unwrap();
        // Add another decision to conv1 with a different file path.
        store
            .log_decision(
                &conv1.id,
                None,
                Decision::Accepted,
                None,
                None,
                "baz.rs",
                0,
                3,
                None,
                None,
            )
            .unwrap();

        let results = store.all_conversations_with_stats(10).unwrap();
        assert_eq!(results.len(), 2);

        // conv1 was updated more recently (because add_message touches updated_at).
        // Find conv1 in results.
        let c1 = results.iter().find(|(c, _, _)| c.id == conv1.id).unwrap();
        assert_eq!(c1.1, 2); // 2 distinct file paths in edit_decisions
        assert_eq!(c1.2, 2); // 2 messages

        let c2 = results.iter().find(|(c, _, _)| c.id == conv2.id).unwrap();
        assert_eq!(c2.1, 0); // no decisions
        assert_eq!(c2.2, 0); // no messages
    }

    #[test]
    fn test_decision_filter() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, None, None)
            .unwrap();
        store
            .log_decision(
                &conv.id,
                None,
                Decision::Accepted,
                None,
                None,
                "test.rs",
                0,
                5,
                None,
                None,
            )
            .unwrap();
        store
            .log_decision(
                &conv.id,
                None,
                Decision::Rejected,
                None,
                None,
                "test.rs",
                0,
                5,
                None,
                None,
            )
            .unwrap();

        let accepted = store
            .query_decisions(None, Some(Decision::Accepted))
            .unwrap();
        assert_eq!(accepted.len(), 1);

        let rejected = store
            .query_decisions(None, Some(Decision::Rejected))
            .unwrap();
        assert_eq!(rejected.len(), 1);
    }

    #[test]
    fn test_create_conversation_with_git_context() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, Some("abc1234"), Some("main"))
            .unwrap();
        assert_eq!(conv.git_commit.as_deref(), Some("abc1234"));
        assert_eq!(conv.branch.as_deref(), Some("main"));

        // Verify round-trip through query.
        let found = store.get_conversation(&conv.id).unwrap().unwrap();
        assert_eq!(found.git_commit.as_deref(), Some("abc1234"));
        assert_eq!(found.branch.as_deref(), Some("main"));
    }

    #[test]
    fn test_decision_with_git_context() {
        let store = ConversationStore::in_memory().unwrap();
        let conv = store
            .create_conversation("test.rs", 0, 10, None, None)
            .unwrap();
        let decision = store
            .log_decision(
                &conv.id,
                None,
                Decision::Accepted,
                None,
                None,
                "test.rs",
                0,
                5,
                Some("def5678"),
                Some("feature-branch"),
            )
            .unwrap();
        assert_eq!(decision.git_commit.as_deref(), Some("def5678"));
        assert_eq!(decision.branch.as_deref(), Some("feature-branch"));

        // Verify round-trip through query.
        let decisions = store.query_decisions(None, None).unwrap();
        assert_eq!(decisions.len(), 1);
        assert_eq!(decisions[0].git_commit.as_deref(), Some("def5678"));
        assert_eq!(decisions[0].branch.as_deref(), Some("feature-branch"));
    }
}
